// <auto-generated />
namespace MVCProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedproduct_order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedproduct_order));
        
        string IMigrationMetadata.Id
        {
            get { return "202106162126592_updated product_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
